### ISSUE TITLE
i can not calibrate or move the position of the arrow

### ISSUE THREAD

**Issue by mnick7507** [sharkyh20/KinectToVR#19]

**Comment by dragonash2019** [comment]
this has been addressed.
It should be fixed by uninstalled your current versions of 2010 and 2017 redistributables and installing the specific ones sharky provided.

That's exactly what I had to do.

**Comment by kyleponiki** [comment]
Re-installing the redistributables did not work for me. What should I do?

**Comment by earmbrust** [comment]
I have two year old redistributables, but still have the same issue.  Mine are newer than the ones sharky provides, but I have to wonder why he's building to such outdated versions for the releases.  There surely is a solution.  Has anyone checked logs?

**Comment by earmbrust** [comment]
I've removed all redists and installed only the ones provided here.  Same result.

**Comment by Kidsnd274** [comment]
Same issue here, I've had to swap between SteamVR and the Oculus Dash to manually adjust the calibration settings until they fit. Very often only one control works (either Rotation works or moving the arrow works, but never both). I'm using the Oculus Rift S.

**Comment by kyleponiki** [comment]
@Kidsnd274 From what I could gather, the program never supported my headset's controllers. I assume the same situation applies to you. The Rift S is a relatively new headset and the program probably doesn't support the control scheme. Either way, K2VR isn't being developed at the moment, so I would recommend just getting Driver4VR. It would probably save you a lot of hassle.
